[main]
app=bestida
title=Bestida
description=Bestida
language=en-AU
app_homepage=https://google.com.au/
app_version=0.1.0
api_version=v1
api_path=/api/${api_version}
openapi_url=${api_path}/${app}.json
host=localhost
port=5100
# Uvicorn worker processes/threads to handle incoming requests
# +ve for processes, -ve for threads
# Gunicorn uses --workers for process and --threads for threads
# therefor Gunicorn brokers should always be +ve
# recommended 2-4 workers per core (2-4 * number of core)
brokers=2

[gravatar]
url=https://www.gravatar.com/avatar
size=100
default=mm
rating=g

[cors]
origins = [
          "http://localhost:5100",
          "http://localhost"
        ]

[token]
# 60 minutes * 24 hours = 1440 minutes
expire_minutes=1440
# openssl rand -hex 32
secret=1dc8c547a91188fc62ae9c22f1404d504e2894ef11cdb2008f1479867537b296
jwt_algorithm=HS256

[themes]
dark = dark
light = corporate

[defaults]
country=AU
currency=AUD
locale=en-au
timezone=Australia/Melbourne
# expiry days
# to reflect changes immediately : delete ./cache/form_schema_Users
user_expiry=30
password_expiry=365

[paths]
base=/home/gvv/Projects/${main:app}
src=${base}/src

[sqlalchemy]
#url=sqlite:///${paths:src}/${main:app}.sqlite
url=postgresql://gvv:11gv1327@/bestida

[image]
location = ${paths:base}/images
public=/images
# bytes: 5 * 1024 * 1024 = 5MB
file_max_size = 5242880
formats = ["JPEG", "PNG", "WEBP"]

[dump]
location = ${paths:base}/dump

[workfile]
location = ${paths:base}/temp
# bytes: 10 * 1024 * 1024 = 10MB
file_max_size = 10485760
mime_types = ["text/plain", "application/csv"]

[release]
location = ${paths:base}/release

[static]
location = ${paths:src}/static
public=/static

[templates]
location = ${paths:src}/templates

[spooler]
location = ${paths:base}/spools
public=/spools
keepdays = 3

[cache]
tables=true
fields=true
# grids=false to allow debug
grids=false
# forms=false to allow child formSchema main_form=False option
forms=false
location = ${paths:base}/cache
# Time To Live (ttl) the amount of time (in seconds) that each item should be kept
# in the cache before being evicted.
# 60 seconds * 60 minutes * 24 hours = 86400 seconds
ttl = 86400

[jobqs]
keys = Express, Batch

[jobq_Batch]
start = true
# process interval in secs (check jobs every n seconds), defaults to 10 secs
interval = 10
# poolsize == 0 or not defined, will use cpu_count
# poolsize is number of process
poolsize = 1

[jobq_Express]
start = true
# process interval in secs (check jobs every n seconds), defaults to 10 secs
interval = 10
# poolsize == 0 or not defined, will use cpu_count
# poolsize is number of process
poolsize = 2

[email]
# https://stackoverflow.com/questions/60975490/how-does-one-send-an-e-mail-from-python-not-using-gmail
# https://support.google.com/mail/thread/205453566/how-to-generate-an-app-password?hl=en
# How to get an app password    https://myaccount.google.com/apppasswords
host=smtp.gmail.com
port=587
username=gvverdad@gmail.com
password=tgxdhprthqklelar
tls=True
default_sender=admin@gvv.com.au

[logs]
location = ${paths:base}/logs

# logging configuration
[loggers]
keys = root, uvicorn, gunicorn.error, gunicorn.access, sqlalchemy

[handlers]
keys = rotatingFileRoot, rotatingFileUvicorn, rotatingFileGunicorn, rotatingFileGunicornAccess, rotatingFileSqlalchemy

[formatters]
keys = generic

# logging levels
#    CRITICAL: Critical errors that lead to a complete failure of the operation.
#    ERROR: Errors that prevent the successful execution of an operation.
#    WARNING: Warnings about potential issues or situations that may cause problems.
#    INFO: Informational messages that provide status updates and progress.
#    DEBUG: Detailed debugging messages that help diagnose issues.
#    NOTSET: The lowest logging level that disables all logging.
# sqlalchemy
# "level = INFO" logs SQL queries.
# "level = DEBUG" logs SQL queries and results.
# "level = WARNING" logs neither.  (Recommended for production systems.)
#
[logger_root]
level = DEBUG
handlers = rotatingFileRoot

[logger_uvicorn]
level = INFO
handlers = rotatingFileUvicorn
qualname = uvicorn

[logger_gunicorn.error]
level = INFO
handlers = rotatingFileGunicorn
qualname = gunicorn.error

[logger_gunicorn.access]
level = INFO
handlers = rotatingFileGunicornAccess
qualname = gunicorn.access

[logger_sqlalchemy]
level = WARNING
handlers = rotatingFileSqlalchemy
qualname = sqlalchemy.engine

# The logger level acts as an initial filter for log messages,
# and the handler level acts as a secondary filter for messages that pass the
# logger's filter
[handler_rotatingFileRoot]
class=handlers.TimedRotatingFileHandler
level=DEBUG
formatter=generic
args=('logs/root.log', 'midnight', 1, 30)

[handler_rotatingFileUvicorn]
class=handlers.TimedRotatingFileHandler
level=DEBUG
formatter=generic
args=('logs/uvicorn.log', 'midnight', 1, 30)

[handler_rotatingFileGunicorn]
class=handlers.TimedRotatingFileHandler
level=DEBUG
formatter=generic
args=('logs/gunicorn.log', 'midnight', 1, 30)

[handler_rotatingFileGunicornAccess]
class=handlers.TimedRotatingFileHandler
level=DEBUG
formatter=generic
args=('logs/access.log', 'midnight', 1, 30)

[handler_rotatingFileSqlalchemy]
class=handlers.TimedRotatingFileHandler
level=DEBUG
formatter=generic
args=('logs/sqlalchemy.log', 'midnight', 1, 30)

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s:%(lineno)s][%(threadName)s] %(message)s
