from . import CustomerAddresses
from . import CustomerAddressTypes
from . import CustomerAgeingGroups
from . import CustomerAllocationGroups
from . import CustomerCancelGroups
from . import CustomerClasses
from . import CustomerContacts
from . import CustomerContactTypes
from . import CustomerDespatchGroups
from . import CustomerEmails
from . import CustomerEmailTypes
from . import CustomerGroups
from . import CustomerKeywords
from . import CustomerPackingGroups
from . import CustomerPhones
from . import CustomerPhoneTypes
from . import CustomerPickingGroups
from . import CustomerPriceBands
from . import CustomerPriorities
from . import CustomerProcessingGroups
from . import CustomerRegions
from . import CustomerReportingGroups
from . import CustomerReturnsGroups
from . import Customers
from . import CustomerSalesGroups
from . import CustomerStatementGroups
from . import CustomerStoreAddresses
from . import CustomerStoreContacts
from . import CustomerStoreEmails
from . import CustomerStorePhones
from . import CustomerStores
from . import CustomerTypes
from . import CustomerWarehouseAddresses
from . import CustomerWarehouseContacts
from . import CustomerWarehouseEmails
from . import CustomerWarehousePhones
from . import CustomerWarehouses
