from . import PersonAddresses
from . import PersonAddressTypes
from . import PersonEmails
from . import PersonEmailTypes
from . import PersonGenders
from . import PersonPhones
from . import PersonPhoneTypes
from . import Persons
from . import PersonTitles
